name: Node.js CI

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
          cache: npm

      - run: npm ci --ignore-scripts --loglevel verbose
      - run: .\node_modules\.bin\tsc -p node_modules\touchportal-api\tsconfig.json
      - run: npm run pkg-all

      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "Installers/*.tpp"
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
          file_glob: true
